import type { PortfolioData } from './types';
const LOGO_URL = new URL('./pics/gemini-2.5-flash-image-preview (nano-banana)_a_Design_a_higshly_deta.png', import.meta.url).href;

export const DEFAULT_PORTFOLIO_DATA: PortfolioData = {
    name: 'Merad Abderrahim',
    logoUrl: LOGO_URL,
    navLinks: [
        { href: '#about', label: 'About' },
        { href: '#skills', label: 'Skills' },
        { href: '#projects', label: 'Projects' },
        { href: '#experience', label: 'Experience' },
        { href: '#contact', label: 'Contact' },
    ],
    hero: {
        greeting: "Hi, I'm",
        name: 'Merad Abderrahim',
        title: 'Aeronautic Engineer & Multimedia Designer',
        subtitle: "I'm a multidisciplinary creative professional specializing in aeronautical engineering, graphic design, and 3D animation. I leverage technical design and modern web technologies to deliver engaging visual experiences.",
        callToAction1: 'View My Work',
        callToAction2: 'Get In Touch',
    },
    about: {
        imageUrl: LOGO_URL,
        p1: 'I am an Aeronautic Engineer with hands-on experience in airport operations, research-lab environments, and multimedia design. I am a native Arabic speaker, certified in English, and have basic proficiency in French. My skills include strong technical design, rapid-prototyping, and research-support, with a proven ability to collaborate in multicultural teams.',
        p2: 'As a multidisciplinary creative professional, I specialize in graphic design, video editing, website development, and 3D animation. I am experienced in both digital and multimedia design, with hands-on expertise in branding, content creation, and animation using tools like the Adobe Creative Suite and Blender.',
        p3: 'I am proficient in delivering engaging visual experiences and dynamic digital solutions for diverse clients and business needs.',
    },
    skills: [
        { name: 'SolidWorks' },
        { name: 'ANSYS' },
        { name: 'MATLAB' },
        { name: 'Blender' },
        { name: 'nTOPOLOGY' },
        { name: 'Illustrator' },
        { name: 'Photoshop' },
        { name: 'Premiere Pro' },
        { name: 'After Effects' },
    ],
    projects: [
        {
            title: 'TRAXY Solar Energy Campaign',
            description: 'A social media campaign banner designed to promote TRAXY\'s clean and renewable solar energy solutions, emphasizing efficiency and savings.',
            image: new URL('./pics/slide2.png', import.meta.url).href,
            category: 'Graphic Design',
            tags: ['Photoshop', 'Illustrator', 'Branding', 'Social Media'],
            repoUrl: '#',
        },
        {
            title: 'Fiat Abarth 500 - Forest Drive',
            description: 'A realistic 3D render of a Fiat Abarth 500 in a dynamic forest setting. This project focused on photorealistic lighting, texturing, and motion blur.',
            image: new URL('./pics/Td.png', import.meta.url).href,
            category: '3D Renders',
            tags: ['Blender', '3D Modeling', 'Rendering', 'Texturing'],
            repoUrl: '#',
        },
        {
            title: 'Abstract Orbital Camera Lens',
            description: 'A conceptual 3D model exploring intricate mechanical designs, focusing on reflective surfaces, depth of field, and abstract aesthetics.',
            image: new URL('./pics/shooting1.png', import.meta.url).href,
            category: '3D Renders',
            tags: ['Blender', '3D Modeling', 'Rendering', 'Texturing'],
            repoUrl: '#',
        },
        {
            title: 'OLLA Scholar Agency photography Workshop',
            description: 'A conceptual 3D model exploring intricate mechanical designs, focusing on reflective surfaces, depth of field, and abstract aesthetics.',
            image: new URL('./pics/WhatsApp Image 2025-11-04 à 14.35.40_249d3a58.jpg', import.meta.url).href,
            category: 'Graphic Design',
            tags: ['Photoshop', 'Illustrator', 'Branding', 'Social Media'],
            repoUrl: '#',
        },  
        {
            title: 'OLLA Scholar Agency sign language Workshop',
            description: 'A conceptual 3D model exploring intricate mechanical designs, focusing on reflective surfaces, depth of field, and abstract aesthetics.',
            image: new URL('./pics/WhatsApp Image 2025-11-04 à 14.36.22_30550af3.jpg', import.meta.url).href,
            category: 'Graphic Design',
            tags: ['Photoshop', 'Illustrator', 'Branding', 'Social Media'],
            repoUrl: '#',
        },   
        {
            title: 'OLLA Scholar Agency story Template',
            description: 'A conceptual 3D model exploring intricate mechanical designs, focusing on reflective surfaces, depth of field, and abstract aesthetics.',
            image: new URL('./pics/WhatsApp Image 2025-11-04 à 14.35.55_1c7c1033.jpg', import.meta.url).href,
           category: 'Graphic Design',
            tags: ['Photoshop', 'Illustrator', 'Branding', 'Social Media'],
            repoUrl: '#',
        },
           {
            title: 'TRAXY Security Solutions Brochure',
            description: 'A trifold brochure for TRAXY, detailing their personalized video surveillance solutions. The design maintains brand consistency and presents information clearly.',
            image: new URL('./pics/m2.png', import.meta.url).href,
            category: 'Graphic Design',
            tags: ['Illustrator', 'InDesign', 'Print Design', 'Branding'],
            repoUrl: '#',
        },
        {
            title: 'TRAXY Security Camera Promotion',
            description: 'An eye-catching social media post for TRAXY, promoting their real-time security camera systems and installation services.',
            image: new URL('./pics/post1_1.png', import.meta.url).href,
            category: 'Graphic Design',
            tags: ['Photoshop', 'Social Media', 'Marketing'],
            repoUrl: '#',
        },
        {
            title: 'OLLA Scholar Agency Post',
            description: 'A celebratory social media graphic for OLLA Scholar, capturing a team moment and reinforcing the agency\'s brand identity.',
            image: new URL('./pics/h.png', import.meta.url).href,
            category: 'Graphic Design',
            tags: ['Photoshop', 'Branding', 'Social Media'],
            repoUrl: '#',
        },
        {
            title: 'Personal Portfolio Website',
            description: 'Designed and developed a personal portfolio website using modern web technologies to showcase my skills and projects in an interactive way.',
            image: new URL('./pics/gemini-2.5-flash-image-preview (nano-banana)_a_Design_a_highly_deta.png', import.meta.url).href,
            category: 'Websites',
            tags: ['React', 'TypeScript', 'TailwindCSS', 'UI/UX'],
            liveUrl: 'https://portfolio-new-kappa-lime.vercel.app',
            repoUrl: '#',
        },
        {
            title: 'Traxy Website',
            description: 'Designed with figma',
            image: new URL('./pics/454946305_491715493606871_8274298379043921406_n.jpg', import.meta.url).href,
            category: 'Websites',
            tags: ['React', 'TypeScript', 'TailwindCSS', 'UI/UX'],
            liveUrl: 'traxy.org',
            repoUrl: '#',
        },
                {
            title: 'Dzair Sale Store Website',
            description: 'Designed with shopify',
            image: new URL('./pics/1.png', import.meta.url).href,
            category: 'Websites',
            tags: ['React', 'TypeScript', 'TailwindCSS', 'UI/UX'],
            liveUrl: 'https://dzairsale-pt.com/',
            repoUrl: '#',
        },
        {
            title: 'OLLA Scholar Agency Video Highlights',
            description: 'A collection of video content showcasing OLLA Scholar Agency\'s workshops and activities.',
            videoUrl: new URL('./pics/WhatsApp Vidéo 2025-11-04 à 14.35.11_3b01d2aa.mp4', import.meta.url).href,
            category: 'Video Editing',
            tags: ['Video Editing', 'Motion Graphics', 'Social Media'],
            repoUrl: '#',
        },
        {
            title: 'OLLA Scholar Agency Event Coverage',
            description: 'Event coverage and promotional video content for OLLA Scholar Agency.',
            videoUrl: new URL('./pics/finall.mp4', import.meta.url).href,
            category: 'Video Editing',
            tags: ['Video Production', 'Event Coverage', 'Social Media'],
            repoUrl: '#',
        },
        {
            title: 'OLLA Scholar Promotional Video',
            description: 'Promotional video content highlighting OLLA Scholar Agency\'s mission and activities.',
            videoUrl: new URL('./pics/final.mp4', import.meta.url).href,
            category: 'Video Editing',
            tags: ['Video Production', 'Marketing', 'Branding'],
            repoUrl: '#',
        },
        {
            title: 'OLLA Scholar Community Engagement',
            description: 'Video documentation of community engagement and workshop activities.',
            videoUrl: new URL('./pics/WhatsApp Vidéo 2025-11-04 à 14.33.42_9fd9c449.mp4', import.meta.url).href,
            category: 'Video Editing',
            tags: ['Video Production', 'Community Engagement', 'Documentary'],
            repoUrl: '#',
        },
        {
            title: 'OLLA Scholar Animated Logo',
            description: 'Motion graphics animation featuring the OLLA Scholar Agency logo.',
            videoUrl: new URL('./pics/an_logo.mp4', import.meta.url).href,
            category: 'Video Editing',
            tags: ['Motion Graphics', 'Animation', 'Branding'],
            repoUrl: '#',
        },
        {
            title: 'Brand Video for GPS Traxy',
            description: 'Conceptualized, edited, and produced a promotional video for GPS Traxy, showcasing motion graphics and editing skills.',
            videoUrl: new URL('./pics/Traxy.mp4', import.meta.url).href,
            category: 'Video Editing',
            tags: ['Video Production', 'Motion Graphics', 'Corporate'],
            repoUrl: '#',
        },
        {
            title: 'Engineering Design Project',
            description: 'A comprehensive engineering project showcasing various design iterations and 3D models created using SOLIDWORKS and Blender.',
            images: [
                new URL('./pics/WhatsApp Image 2025-10-30 à 20.47.42_bd4cf888.jpg', import.meta.url).href,
                new URL('./pics/WhatsApp Image 2025-10-30 à 20.47.42_185f0cc5.jpg', import.meta.url).href,
                new URL('./pics/WhatsApp Image 2025-10-30 à 20.47.42_8f5b7418.jpg', import.meta.url).href,
                new URL('./pics/Untitled.png', import.meta.url).href,
                new URL('./pics/WhatsApp Image 2025-10-30 à 20.47.42_7a15b019.jpg', import.meta.url).href
            ],
            category: 'Engineering',
            tags: ['SOLIDWORKS', 'Blender', '3D Modeling', 'Engineering Design'],
            liveUrl: '',
            repoUrl: '#',
        },
    ],
    videos: [],
    
    experience: [
        {
            role: 'Intern',
            company: 'MSN Laboratory, Batna, Algeria',
            period: '2023 - 2024',
            description: [
                'Supported aerodynamic research by preparing scale models and assisting with wind-tunnel experiments.',
                'Collected and processed test data using MATLAB and Excel, and drafted technical summaries in English.',
                'Operated a 3D printer for rapid prototype fabrication and conducted traction testing using a press machine.',
                'Collaborated on design iterations and maintained lab safety protocols.',
            ],
        },
        {
            role: 'Intern',
            company: 'Mostéfa Ben Boulaïd Airport, Batna, Algeria',
            period: '2023 - 2024',
            description: [
                'Visited and observed operations in the Navigation Control Center, Fuel Station, ENNA facilities, Meteorology Office, Maintenance Hangar, Energy Management Section, and Warehouse.',
            ],
        },
        {
            role: 'Designer & Video Editor',
            company: 'GPS Traxy, Batna, Algeria',
            period: '2022 - 2023',
            description: [
                'Specialized in graphic design, video editing, and 3D animation.',
                'Experienced in both digital and multimedia design, with hands-on expertise in branding and content creation.',
                'Utilized Adobe Creative Suite and Blender to deliver engaging visual experiences.',
            ],
        },
    ],
    contact: {
        email: 'xrahimo0542@gmail.com',
        githubUrl: 'https://github.com/xrahimo0542',
        linkedinUrl: 'https://www.linkedin.com/in/rahim-merad-7653752aa/',
    }
};
